server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/collectin
    url: jdbc:postgresql://collection.cwadb5ddtdy3.us-east-1.rds.amazonaws.com:5432/collectin
    username: postgres
    password: AB5939523
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
#            clientId: 215239766030-sptnp2do56k1irr2i4tqt62qavdo1m3m.apps.googleusercontent.com # mine
#            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 2133731386805721
            clientSecret: 88a56d10299e42bba111000ee6f62f34
#            clientId: 121189305185277
#            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
#            clientId: 1bcba39edc8f39ee618a
#            clientSecret: b563b4bb80da03d206a7c73362a77d85649ea5d3
            clientId: 748acff4c2f38d0541a3
            clientSecret: 2e702ced9f775830e79747be1fec739364446cc0
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://3.95.203.15:3000,http://localhost:8080,http://3.95.203.15:8080
  oauth2:
    authorizedRedirectUris:
#      - http://localhost:3000/oauth2/redirect
      - http://3.95.203.15:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

jwt:
  access:
    secret:
      key: mysupersecretkey_w243t5@dvbsWEF#aegLNUGPn$dfvrom%fbwr4330$rfsvmaetr>
    expiration:
      time: 6000000
  refresh:
    secret:
      key: mysupersecretkey^fdsgZXSS*efwget()efgwwWEF3$!fdsg49302rAEFWRggjOHI>
    expiration:
      time: 360000000

firebase:
  bucket:
    name: collectin-3959d.appspot.com
  image:
    url: https://firebasestorage.googleapis.com/v0/b/${firebase.bucket.name}/o/%s?alt=media
  project:
    id: collectin-3959d
api:
  info:
    title: CollectIn
    description: This is online collection managment web-site. You can collect and save anything you want!
    version: 1.0
    termOfService: https://github.com/Bekzod-Murotboyev/collect_in_backend
    contact-name: CollectIn
    contact-email: https://github.com/Bekzod-Murotboyev/collect_in_backend
    contact-url: https://github.com/Bekzod-Murotboyev/collect_in_backend
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs